import Foundation

public enum SpinnerPattern {
  public static let no1 = "|/-\\"
  public static let no2 = "⠂-–—–-"
  public static let no3 = "◐◓◑◒"
  public static let no4 = "◴◷◶◵"
  public static let no5 = "◰◳◲◱"
  public static let no6 = "▖▘▝▗"
  public static let no7 = "■□▪▫"
  public static let no8 = "▌▀▐▄"
  public static let no9 = "▉▊▋▌▍▎▏▎▍▌▋▊▉"
  public static let no10 = "▁▃▄▅▆▇█▇▆▅▄▃"
  public static let no11 = "←↖↑↗→↘↓↙"
  public static let no12 = "┤┘┴└├┌┬┐"
  public static let no13 = "◢◣◤◥"
  public static let no14 = ".oO°Oo."
  public static let no15 = ".oO@*"
  public static let no16 = "🌍🌎🌏"
  public static let no17 = "◡◡ ⊙⊙ ◠◠"
  public static let no18 = "☱☲☴"
  public static let no19 = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"
  public static let no20 = "⠋⠙⠚⠞⠖⠦⠴⠲⠳⠓"
  public static let no21 = "⠄⠆⠇⠋⠙⠸⠰⠠⠰⠸⠙⠋⠇⠆"
  public static let no22 = "⠋⠙⠚⠒⠂⠂⠒⠲⠴⠦⠖⠒⠐⠐⠒⠓⠋"
  public static let no23 = "⠁⠉⠙⠚⠒⠂⠂⠒⠲⠴⠤⠄⠄⠤⠴⠲⠒⠂⠂⠒⠚⠙⠉⠁"
  public static let no24 = "⠈⠉⠋⠓⠒⠐⠐⠒⠖⠦⠤⠠⠠⠤⠦⠖⠒⠐⠐⠒⠓⠋⠉⠈"
  public static let no25 = "⠁⠁⠉⠙⠚⠒⠂⠂⠒⠲⠴⠤⠄⠄⠤⠠⠠⠤⠦⠖⠒⠐⠐⠒⠓⠋⠉⠈⠈"
  public static let no26 = "⢄⢂⢁⡁⡈⡐⡠"
  public static let no27 = "⢹⢺⢼⣸⣇⡧⡗⡏"
  public static let no28 = "⣾⣽⣻⢿⡿⣟⣯⣷"
  public static let no29 = "⠁⠂⠄⡀⢀⠠⠐⠈"
  public static let no30 = "🌑🌒🌓🌔🌕🌝🌖🌗🌘🌚"
}

